project_id = "tlgdwlkjkyregpogdtbf"

[functions.invite-user]
verify_jwt = false

[functions.impersonate-client]
verify_jwt = true

[functions.send-project-email]
verify_jwt = false

[functions.log-activity]
verify_jwt = false